{
 "title": "Air quality",
 "tags": [ "home" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(alpstuga_temperature_celsius)",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Current CO2 Levels",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(alpstuga_co2_ppm)", "legendFormat": "{{room}}" }
   ]
  },
  {
   "title": "Current Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alpstuga_relative_humidity_percent",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Current PM2.5 Levels",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µg/m³" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(alpstuga_pm25_micrograms_per_cubic_meter)",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "round(avg by(room) (alpstuga_temperature_celsius), 0.1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(room) (alpstuga_relative_humidity_percent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Carbon dioxide",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "avg by(room) (alpstuga_co2_ppm)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Particulate Matter (PM2.5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µg/m³" } },
   "targets": [
    {
     "expr": "avg by(room) (alpstuga_pm25_micrograms_per_cubic_meter)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}